name: flutter_wallet
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # plugin_platform_interface: ^2.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.djinnapps.wallet.flutter_wallet
        pluginClass: FlutterWalletPlugin
      ios:
        pluginClass: FlutterWalletPlugin